services:

  nginx:
    image: nginx:1.17.5-alpine
    depends_on:
      - app
      - postgres
    restart: always
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - "80:80"

  app:
    build: ./
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always


  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql-database:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"

volumes:
  postgresql-database:
    name: postgresql-database