name: Deploy FastAPI to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=$(date +%s)  # Use a timestamp-based tag
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:$IMAGE_TAG .
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:$IMAGE_TAG

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/fastapi
          sudo docker compose down  # Stop old containers
          sudo docker compose -f docker-compose_prod.yaml up -d --remove-orphans
          sudo docker system prune -f  # Cleanup unused images
