name: Deploy FastAPI to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:latest .
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:latest

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo cd ~/fastapi  # Make sure this is your deployment directory
          git pull origin main  # If you're storing your `docker-compose.yml` in a repo
          sudo docker compose down  # Stop old containers
          sudo docker compose pull  # Pull latest images
          sudo docker compose up -d --remove-orphans  # Start new containers
          sudo docker system prune -f  # Cleanup unused images
